### ISSUE TITLE
Marker at the edge of the duration does not show

### ISSUE THREAD

**Issue by jodonnell** [bbc/peaks.js#303] opened 2020-01-23 14:44 UTC
We are trying to render a point marker at the duration of the audio file so it should be at the right edge.  I have already customized our particular marker to flip the flag so it goes to the left.  The problem is at the far left it doesn't show at all, i believe konva or something thinks its not in view so don't bother to render it.  So far I've been resorting to to subtracting .05 seconds, but it seems that doesn't work all the time and instead i might need to scale this based on the duration.  Also we have a couple other places that are importing markers that lives outside the frontend which would require copying this logic to backend scripts.  

So it would be preferable if this was fixed.  If you don't have time, if you could point me in the right direction, I _may_ have some time to look into it.

Thanks!

**Comment by chrisn** [comment] 2020-01-27 17:18
I guess one of the latest changes I made on the `marker-customisation` branch won't work for you (replacing `positionUpdated` with `timeUpdated`) as you would want to draw the marker differently when it's scrolled near to the edge of the container. Sounds like I should reintroduce `positionUpdated` in this case.

**Comment by jodonnell** [comment] 2020-01-27 17:55
well we actually have a marker type always flipped because its expected to be at the end.

so to be clear rather than saying is this marker near the end?  then flip it.

we pass in a little metadata thats set by clicking a button in the ui to the marker function that says if this is true flip it.

**Comment by chrisn** [comment] 2020-01-27 18:06
OK, I'll leave the API as is then, and see if we get further feedback once its merged.

I'm able to reproduce the issue of markers at the end of the audio not being drawn, using `demo/multi-channel.html`.

For the zoomview I guess we could extend the scroll range beyond the end of the audio duration a little. But we'd need a different solution for the overview, which is intended to fit the available width exactly. I'll investigate...

**Comment by jodonnell** [comment] 2020-01-27 22:58
Thank you.

**Comment by chrisn** [comment] 2020-01-28 19:56
I've done a couple of tests using the Peaks.js demo pages:

**demo/multi-channel.html**

On this page, `mediaElement.duration` returns 15.177143 seconds. A point marker placed at this time is not visible.

If I convert the MP3 to WAV format (using [audiowaveform](https://github.com/bbc/audiowaveform)), and the duration of the WAV audio is reported as 15.152086. A point marker placed at this time _is_ visible.

Switching the **Select source** option on this page from **Remote** (precomputed .dat file) to **Web Audio**,  I see that 668,207 samples are processed, at a sample rate of 44.1kHz, which is a duration of 15.152086167800453 seconds. This agrees with the `audiowaveform` output.

**demo/web-audio.html**

On this page, `mediaElement.duration` returns 377.338776. A point marker placed at this time is not visible.

Computing the waveform using Web Audio, I see that 16,639,535 samples are processed, at a sample rate of 44.1kHz, which is a duration of 377.31371882086165 seconds. A point marker placed at this time _is_ visible.

**Conclusion**

From this, we can see that the browser doesn't report the correct audio duration for MP3 files. If you want to place a marker at the end of the audio, you need to use the actual audio duration, as computed when the waveform is generated, as Peaks.js uses this duration to determine the visible waveform length.

A possible solution here is to add an API method to return the actual computed audio duration.

**Comment by jodonnell** [comment] 2020-01-28 22:11
Hi Chris, our backend returns the asset length, so now we are returning the wav duration rather than the mp3 duration.  This fixes it for us.  I'll leave it up to you if you want to close this ticket or not.

Thank you!

**Comment by chrisn** [comment] 2020-01-28 22:19
Thanks, I'll close this with no change.

**Closed by chrisn** 2020-01-28 22:19 UTC
