### ISSUE TITLE
Scrubbing always reset to start position

### ISSUE THREAD

**Issue by loretoparisi** [bbc/peaks.js#245] opened 2018-11-22 15:10 UTC
My implementation looks like

```javascript
(function (Peaks) {
                var myAudioContext = new AudioContext();
                var p = Peaks.init({
                    container: document.querySelector('#media_waveform'),
                    mediaElement: document.querySelector('audio'),
                    audioContext: myAudioContext
                });
                p.on('peaks.ready', function () {
                    // do something when the waveform is displayed and ready
                    platform.UpdateUIProgressBar('waveform_progress', 100, 'Done.');
                });
            })(peaks);
```

When scrubbing and releasing the mouse, the player bar is always resetting to the starting position.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/163333/48910761-0fe23c00-ee71-11e8-80ff-9de0ba47146e.gif)

**Comment by chrisn** [comment] 2018-11-22 22:13
Thanks for reporting this, Loreto. This is a duplicate of #233.

**Closed by chrisn** 2018-11-22 22:13 UTC

**Comment by loretoparisi** [comment] 2018-11-23 09:12
@chrisn ok I have reported there my feedback, I have found a strange behavior on Chrome about range headers please check there.
