### ISSUE TITLE
Does Peaks.js work with DVR live streaming? If yes, can you provide some examples with DASH streaming?

### ISSUE THREAD

**Issue by lucianogrippa** [bbc/peaks.js#364] opened 2021-02-04 16:49 UTC
I'm working on an audio editor and I need partial or total representation of the audio wave from DVR live even when the window is moving and  I need to know  if is possible with this library.

**Comment by chrisn** [comment] 2021-02-04 16:59
It doesn't currently work with DASH streaming, only file based media. This would be a very welcome addition, though, if you or someone is interested to work on it.

**Comment by chrisn** [comment] 2024-12-07 17:55
Closing, as this is essentially a duplicate of #131.

**Closed by chrisn** 2024-12-07 17:55 UTC
