### ISSUE TITLE
Providing the ArrayBuffer directly as an object

### ISSUE THREAD

**Issue by janhartmann** [bbc/peaks.js#228] opened 2018-06-06 09:26 UTC
I am in a situation where I have the complete AudioBuffer as a JS object, not in a separate `json` or `dat` file, but directly when initialising the Peaks library, like:

```js
const audioBuffer = await this.audioContext.decodeAudioData(dataBuffer);
```

From this, I am able to construct the JSON format, but is there any way to provide a JSON string to the `dataUri` parameter?

**Comment by chrisn** [comment] 2018-06-06 19:47
At present, no. But this seems like a useful thing to be able to do. I'd prefer to see an API that allows you to provide the object directly, rather than by serializing to a JSON string. The [waveform-data.js](https://github.com/bbc/waveform-data.js) module is responsible for providing the data to Peaks.js.

**Comment by chrisn** [comment] 2019-09-11 13:32
I have just published v0.13.0, which lets you intialise a Peaks instance given an `AudioBuffer`. I'll close this issue as resolved, but please re-open if there are any problems. Thanks!

**Closed by chrisn** 2019-09-11 13:32 UTC

**Comment by komikoni** [comment] 2019-11-10 04:19
I am very happy to update this feature.
Previously, Peaks.init was monkey patched.

There is no problem with the operation,
I have a little problem with the Readme.

https://github.com/bbc/peaks.js#web-audio-based-waveforms

```js
const AudioContext = window.AudioContext || window.webkitAudioContext;
const audioContext = new AudioContext();

// arrayBuffer contains the encoded audio (e.g., MP3 format)
audioContext.decodeAudioData(arrayBuffer)
  .then(function(audioBuffer) {
    const options = {
      containers: {
        overview: document.getElementById('overview-waveform'),
        zoomview: document.getElementById('zoomview-waveform')
      },
      mediaElement: document.querySelector('audio'),
      webAudio: {
        audioBuffer: audioBuffer
      }
    };

    Peaks.init(options, function(err, peaks) {
      // Do something when the waveform is displayed and ready
    });
  });
```

However, an error occurs.

`Peaks.init(): You must pass an audioContext or dataUri to render waveform data`

The following will work correctly.

```js
const AudioContext = window.AudioContext || window.webkitAudioContext;
const myAudioContext = new AudioContext();

// arrayBuffer contains the encoded audio (e.g., MP3 format)
myAudioContext .decodeAudioData(arrayBuffer)
  .then(function(audioBuffer) {
    const options = {
      containers: {
        overview: document.getElementById('overview-waveform'),
        zoomview: document.getElementById('zoomview-waveform')
      },
      mediaElement: document.querySelector('audio'),
      audioContext: myAudioContext,
      webAudio: {
        audioBuffer: audioBuffer
      }
    };

    Peaks.init(options, function(err, peaks) {
      // Do something when the waveform is displayed and ready
    });
  });
```

**Comment by chrisn** [comment] 2019-11-10 09:28
@komikoni Thanks! I don't see the same error. If you pass an `AudioBuffer`, Peaks.js doesn't need the `AudioContext`. Are you using the latest release?

**Comment by komikoni** [comment] 2019-11-10 11:45
@chrisn 
Thank you for your reply.

As you say !!
The cause seems to be that caching was effective in browser debugging.
I'm sorry for making a mistake.

Peaks.js is a really great library.
