### ISSUE TITLE
Issue scrolling

### ISSUE THREAD

**Issue by adamteale** [bbc/peaks.js#430] opened 2021-12-07 11:50 UTC
Hi! 

Any ideas what would be causing the segments to not scroll along with the waveform when I drag/scroll along the waveform?
When i hit play it seems to sort of work but isn't so smooth.

Using React & Typescript. Peaks.js 0.27.0

https://user-images.githubusercontent.com/7489774/145024108-70551438-275d-4941-999b-ce5f931262e8.mov

Thanks!

Adam

**Comment by adamteale** [comment] 2021-12-07 15:37
I just tried v0.26.0 and it seems ok

**Comment by chrisn** [comment] 2021-12-10 00:36
I'm not sure what's causing this, it's working OK for me here.

**Comment by tmtakashi** [comment] 2022-02-03 05:48
Hi, this issue seems to happen when `editable` is set to `false` in my environment.
Do you have any idea why this happen @chrisn ?

**Comment by chrisn** [comment] 2022-02-03 20:15
Thanks @tmtakashi. I can reproduce the issue with `editable: false`. I'll investigate...

**Comment by chrisn** [comment] 2022-02-03 23:48
I've just published a new version to npm that should fix this issue. Please update and let me know if it works OK for you.

**Comment by tmtakashi** [comment] 2022-02-04 01:57
It seems to be working with `editable: false` with the update! Thanks for your fast response & fix!

**Comment by chrisn** [comment] 2022-02-06 09:29
@adamteale I'll close this, as I'm hoping your issue is also fixed in v0.28.0m but please re-open if not.

**Closed by chrisn** 2022-02-06 09:29 UTC
